let
    Source = LoqateAPIKey,
    #"Renamed to Addresses" = Table.RenameColumns(Source,{{"LoqatePrepare", "Addresses"}}),
    InitialJson = Json.FromValue(#"Renamed to Addresses"),
    InitialJsonText = Text.FromBinary(InitialJson),
    FinalJsonText = Text.Insert(Text.Middle(InitialJsonText,1,Text.Length(InitialJsonText)-2),Text.Length(InitialJsonText)-3,","&
Character.FromNumber(34)&"Options"&Character.FromNumber(34)&": {"&Character.FromNumber(34)&"Process"&Character.FromNumber(34)&": "&Character.FromNumber(34)&"Verify"&Character.FromNumber(34)&","&Character.FromNumber(34)&"Certify"&Character.FromNumber(34)&":false,"&Character.FromNumber(34)&"ServerOptions"&Character.FromNumber(34)&": {"&Character.FromNumber(34)&"OutputAddressFormat"&Character.FromNumber(34)&": "&Character.FromNumber(34)&"Yes"&Character.FromNumber(34)&","&Character.FromNumber(34)&"AddressLineSeparator"&Character.FromNumber(34)&":"&Character.FromNumber(34)&"/n"&Character.FromNumber(34)&"}}"),
    FinalJson = Json.Document(Web.Contents("https://api.addressy.com/Cleansing/International/Batch/v1.00/json4.ws", [Headers=[#"Content-Type"="application/json"], Content=Text.ToBinary(FinalJsonText)])),
    OutputList = FinalJson,
    #"Converted to Table" = Table.FromList(OutputList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"Input", "Matches"}, {"Column1.Input", "Column1.Matches"}),
    #"Expanded Column1.Matches" = Table.ExpandListColumn(#"Expanded Column1", "Column1.Matches"),
    #"Expanded Column1.Matches1" = Table.ExpandRecordColumn(#"Expanded Column1.Matches", "Column1.Matches", {"AQI", "AVC", "Address", "Address1", "Address2", "Address3", "Administrative Area", "AdministrativeArea", "CountryName", "DeliveryAddress", "DeliveryAddress1", "HyphenClass", "ISO3166-2", "Country", "ISO3166-3", "ISO3166-N", "Locality", "MatchRuleLabel", "PostalCode", "PostalCodePrimary", "Premise", "PremiseNumber", "Thoroughfare", "ThoroughfareName", "ThoroughfareTrailingType", "ThoroughfareType", "Address4", "DeliveryAddress2", "DependentLocality", "Unmatched", "Building", "SubBuilding", "SubBuildingNumber", "Address5", "DeliveryAddress3"}, {"AQI", "AVC", "Address", "Address1", "Address2", "Address3", "Administrative Area", "AdministrativeArea", "CountryName", "DeliveryAddress", "DeliveryAddress1", "HyphenClass", "ISO3166-2", "Country", "ISO3166-3", "ISO3166-N", "Locality", "MatchRuleLabel", "PostalCode", "PostalCodePrimary", "Premise", "PremiseNumber", "Thoroughfare", "ThoroughfareName", "ThoroughfareTrailingType", "ThoroughfareType", "Address4", "DeliveryAddress2", "DependentLocality", "Unmatched", "Building", "SubBuilding", "SubBuildingNumber", "Address5", "DeliveryAddress3"}),
    #"Expanded Column1.Input" = Table.ExpandRecordColumn(#"Expanded Column1.Matches1", "Column1.Input", {"Address", "Address1", "Address2", "Address3", "Address4", "Address5", "Address6", "Address7", "Address8", "Country", "SuperAdministrativeArea", "Administrative Area", "SubAdministrativeArea", "Locality", "DependentLocality", "DoubleDependentLocality", "Thoroughfare", "DependentThoroughfare", "Building", "Premise", "SubBuilding", "PostalCode", "Organization", "PostBox"}, {"Column1.Input.Address", "Column1.Input.Address1", "Column1.Input.Address2", "Column1.Input.Address3", "Column1.Input.Address4", "Column1.Input.Address5", "Column1.Input.Address6", "Column1.Input.Address7", "Column1.Input.Address8", "Column1.Input.Country", "Column1.Input.SuperAdministrativeArea", "Column1.Input.Administrative Area", "Column1.Input.SubAdministrativeArea", "Column1.Input.Locality", "Column1.Input.DependentLocality", "Column1.Input.DoubleDependentLocality", "Column1.Input.Thoroughfare", "Column1.Input.DependentThoroughfare", "Column1.Input.Building", "Column1.Input.Premise", "Column1.Input.SubBuilding", "Column1.Input.PostalCode", "Column1.Input.Organization", "Column1.Input.PostBox"}),
    #"Added ID" = Table.AddColumn(#"Expanded Column1.Input", "ID", each [Column1.Input.Address1]&[Column1.Input.Address2]&[Column1.Input.PostalCode]),
    #"Reordered Columns" = Table.ReorderColumns(#"Added ID",{"ID", "Column1.Input.Address", "Column1.Input.Address1", "Column1.Input.Address2", "Column1.Input.Address3", "Column1.Input.Address4", "Column1.Input.Address5", "Column1.Input.Address6", "Column1.Input.Address7", "Column1.Input.Address8", "Column1.Input.Country", "Column1.Input.SuperAdministrativeArea", "Column1.Input.Administrative Area", "Column1.Input.SubAdministrativeArea", "Column1.Input.Locality", "Column1.Input.DependentLocality", "Column1.Input.DoubleDependentLocality", "Column1.Input.Thoroughfare", "Column1.Input.DependentThoroughfare", "Column1.Input.Building", "Column1.Input.Premise", "Column1.Input.SubBuilding", "Column1.Input.PostalCode", "Column1.Input.Organization", "Column1.Input.PostBox", "AQI", "AVC", "Address", "Address1", "Address2", "Address3", "Administrative Area", "AdministrativeArea", "CountryName", "DeliveryAddress", "DeliveryAddress1", "HyphenClass", "ISO3166-2", "Country", "ISO3166-3", "ISO3166-N", "Locality", "MatchRuleLabel", "PostalCode", "PostalCodePrimary", "Premise", "PremiseNumber", "Thoroughfare", "ThoroughfareName", "ThoroughfareTrailingType", "ThoroughfareType", "Address4", "DeliveryAddress2", "DependentLocality", "Unmatched", "Building", "SubBuilding", "SubBuildingNumber", "Address5", "DeliveryAddress3"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"Column1.Input.Address", "Column1.Input.Address1", "Column1.Input.Address2", "Column1.Input.Address3", "Column1.Input.Address4", "Column1.Input.Address5", "Column1.Input.Address6", "Column1.Input.Address7", "Column1.Input.Address8", "Column1.Input.Country", "Column1.Input.SuperAdministrativeArea", "Column1.Input.Administrative Area", "Column1.Input.SubAdministrativeArea", "Column1.Input.Locality", "Column1.Input.DependentLocality", "Column1.Input.DoubleDependentLocality", "Column1.Input.Thoroughfare", "Column1.Input.DependentThoroughfare", "Column1.Input.Building", "Column1.Input.Premise", "Column1.Input.SubBuilding", "Column1.Input.PostalCode", "Column1.Input.Organization", "Column1.Input.PostBox", "Address", "Address1", "Address2", "Address3", "DeliveryAddress1", "HyphenClass", "ISO3166-2", "Country", "ISO3166-3", "ISO3166-N", "MatchRuleLabel", "PostalCodePrimary", "Premise", "PremiseNumber", "Thoroughfare", "ThoroughfareName", "ThoroughfareTrailingType", "ThoroughfareType", "Address4", "DeliveryAddress2", "DependentLocality", "Unmatched", "Building", "SubBuilding", "SubBuildingNumber", "Address5", "DeliveryAddress3"})
in
    #"Removed Columns"
